Repository kubewarden/policy-fetcher, pull requests merged in 2024-05, with the labels that each got.

#186 E2E test to fetch signature from authenticated registry.
  Cargo.toml
  src/verify/mod.rs
  tests/e2e.rs
Labels: kind/enhancement

#187 update sigstore
  Cargo.toml
  src/store/mod.rs
  src/verify/config.rs
  src/verify/mod.rs
  tests/e2e.rs
Labels: kind/enhancement, area/dependencies

#190 chore: add Kubewarden repository badges.
  README.md
Labels: kind/chore
